### ISSUE TITLE
Hello Tfarcenim

### ISSUE THREAD

**Issue by LeSnow-Ye** [Tfarcenim/Beesourceful#10]
Hello tfarecnim!
I'm a player from China and I think your mod is very good.
So I have translated it to Chinese, and here is the lang file:
[zh_cn.json.txt](https://github.com/Tfarcenim/Beesourceful/files/4720733/zh_cn.json.txt)
(I have to add ".txt" at the end to update it)

In addition,could you please allow me to repost it to the largest Minecraft forum in China [MCBBS](www.mcbbs.net)?
I'll only give the address linked to curseforge and github.

**Comment by Tfarcenim** [comment]
sure
