### ISSUE TITLE
Crash when trying to load in modpack

### ISSUE THREAD

**Issue by NxD136** [Tfarcenim/Beesourceful#11]
No interesting crash message. 

Crash report : 
[crash-2020-07-15_04.01.21-client.txt](https://github.com/Tfarcenim/Beesourceful/files/4923762/crash-2020-07-15_04.01.21-client.txt)

Sent message on the Secret exit Discord in the #other-mods channel.

Thanks,
-Retro

**Comment by Tfarcenim** [comment]
closed due to failure to provide requested logs
