### ISSUE TITLE
[1.15.1] Bee Generation being spammed in console while generating world. (Server)

### ISSUE THREAD

**Issue by Gbergz** [Tfarcenim/Beesourceful#3]
Title explains it^

**Minecraft**: 1.15.1
**Forge**: 30.0.42
**Mod Version:** 1.0.6

**Example**: https://gist.github.com/Gbergz/d28bfb4fe88641faec7273d886b882d9

*Intended or an issue?*
*Just wondering.*

**Comment by Tfarcenim** [comment]
I forgot to remove it because I was having difficulty finding the beehives as they were very rare.  I'll remove it soon, but if you really have a hard time finding the hives, use an xray mod.
