### ISSUE TITLE
Beesourceful bees severely impact game performance

### ISSUE THREAD

**Issue by LyraelRayne** [Tfarcenim/Beesourceful#4]
Hi there, I noticed that with this mod installed my server's average tick time is about 30-50ms (making it often not playable) . Without the mod it's more like 9-20ms, I know it's this mod because JVisualVM tells me that over 30% of the server's time is spent on Bee pathfinding). I suspect this is actually a Minecraft issue with Bees pathfinding underground (or anywhere they can't find flowers). Considering that most of your bees spawn underground with no flowers, you may want to alter the AI somewhat to avoid severe performance problems.

**Comment by Tfarcenim** [comment]
easy fix, don't let the bees out until the player breaks the hive

**Comment by Tfarcenim** [comment]
fixed, beehives no longer tick when initially generated in the world
