### ISSUE TITLE
Potential bug + feature requests

### ISSUE THREAD

**Issue by DrDarkfire** [Tfarcenim/Beesourceful#5]
So, loving what you're doing with this mod. probably my favorite 1.15 mod to exist right now.
As for the potential bug, I'm trying to automate the centrifuge with hopper inputs. However if I were to input bottles without a comb already being in there, it will input into the slot the comb should go. If we could get side inputs like the furnace where side injection goes into the fuel slot, and the top goes into the what we cooking slot.

For feature requests. I would like either modded bees, or the ability to make custom bees. As a pack dev I find it kind of limiting to only be able to have vanilla ores get bees.

Another request is bee breeding where maybe only like ored bees can breed into more of that bee. maybe the breeding item could be the ingot/gem associated with them.

Thanks for reading this and hope my requests get considered.

**Comment by Tfarcenim** [comment]
> As for the potential bug, I'm trying to automate the centrifuge with hopper inputs. However if I were to input bottles without a comb already being in there, it will input into the slot the comb should go. If we could get side inputs like the furnace where side injection goes into the fuel slot, and the top goes into the what we cooking slot.

This has been resolved with the changing of the centrifuge

 > For feature requests. I would like either modded bees, or the ability to make custom bees. As a pack dev I find it kind of limiting to only be able to have vanilla ores get bees.

Working on a data driven system, but 1.16 and life happened

> Another request is bee breeding where maybe only like ored bees can breed into more of that bee. maybe the breeding item could be the ingot/gem associated with them

wat

**Comment by Tfarcenim** [comment]
2.1.0
